export const DORMS = [
  'Select a dorm',
  '10 Winthrop',
  '9-11 Sunset',
  'Blakeley Hall',
  'Bush Hall',
  'Carmichael Hall',
  'CoHo (Community Housing)',
  'Court at Professors Row',
  'Harleston Hall',
  'Haskell Hall',
  'Hill Hall',
  'Hillside Apartments',
  'Hodgdon Hall',
  'Houston Hall',
  'Latin Way Apartments',
  'Lewis Hall',
  'McCollester House',
  'Metcalf Hall',
  'Miller Hall',
  'Richardson House',
  'Simpson House',
  'Stratton Hall',
  'Sophia Gordon Hall',
  'Tilton Hall',
  'Tousey House',
  'West Hall',
  'Wilson House',
  'Wren Hall',
  '1023 Beacon Street (SMFA)',
  '1025 Beacon Street (SMFA)',
  '1047 Beacon Street (SMFA)',
  'Off-Campus'
];